---
name: Build and Release Docker Images
on:
  push:
    branches:
      - main
    tags:
      - v*
  schedule:
    - cron: '0 0 * * *'
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Get the image tag
        id: vars
        run: echo ::set-output name=tag::$([[ "${GITHUB_REF:10}" = "main" ]] && echo "latest" || echo "${GITHUB_REF:11}")
      - name: Build and push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: ${{ github.repository }}/cve
          tags: ${{ github.sha }}
      - uses: azure/container-scan@v0
        with:
          image-name: docker.pkg.github.com/${{ github.repository }}/cve:${{ github.sha }}
          severity-threshold: CRITICAL
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          repository: proum/${{ github.event.repository.name }}
          tags: ${{ steps.vars.outputs.tag }}
      - name: Upload README to Dockerhub
        uses: proum-public/actions/docker/readme-upload@v1
        with:
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
